using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ULinkActor.SourceGenerator;

[Generator]
public sealed class TypedActorSpawnGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetActorClass(ctx))
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<ImmutableArray<INamedTypeSymbol?>> actorTypes = candidates.Collect();

        context.RegisterSourceOutput(actorTypes, static (ctx, actors) =>
        {
            INamedTypeSymbol[] uniqueActors = actors
                .Where(static actor => actor is not null)
                .Select(static actor => actor!)
                .Where(static actor => !actor.IsGenericType && actor.DeclaredAccessibility == Accessibility.Public)
                .GroupBy(
                    static actor => actor.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    StringComparer.Ordinal)
                .Select(static group => group.First())
                .OrderBy(static actor => actor.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                .ToArray();

            if (uniqueActors.Length == 0)
            {
                return;
            }

            string source = GenerateSource(uniqueActors);
            ctx.AddSource("ULinkActorTypedActorSpawnExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? GetActorClass(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax declaration = (ClassDeclarationSyntax)context.Node;

        if (declaration.BaseList is null)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type)
        {
            return null;
        }

        INamedTypeSymbol? messageType = GetTypedActorMessage(type);

        return messageType is null || messageType.TypeKind == TypeKind.Error ? null : type;
    }

    private static INamedTypeSymbol? GetTypedActorMessage(INamedTypeSymbol actorType)
    {
        foreach (INamedTypeSymbol interfaceType in actorType.AllInterfaces)
        {
            if (interfaceType is
                {
                    Name: "IActor",
                    Arity: 1,
                    ContainingNamespace:
                    {
                        Name: "ULinkActor",
                        ContainingNamespace.IsGlobalNamespace: true
                    }
                })
            {
                return interfaceType.TypeArguments[0] as INamedTypeSymbol;
            }
        }

        return null;
    }

    private static string GenerateSource(IReadOnlyList<INamedTypeSymbol> actorTypes)
    {
        StringBuilder source = new();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace ULinkActor;");
        source.AppendLine();
        source.AppendLine("public static class ULinkActorTypedActorSpawnExtensions");
        source.AppendLine("{");

        foreach (INamedTypeSymbol actorType in actorTypes)
        {
            INamedTypeSymbol messageType = GetTypedActorMessage(actorType)!;
            string actorTypeName = actorType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string messageTypeName = messageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string methodName = "Spawn" + SanitizeIdentifier(actorType.Name);

            source.AppendLine($"    public static global::ULinkActor.ActorRef<{messageTypeName}> {methodName}(");
            source.AppendLine("        this global::ULinkActor.ActorSystem system,");
            source.AppendLine($"        {actorTypeName} actor,");
            source.AppendLine("        global::ULinkActor.ActorSpawnOptions? options = null)");
            source.AppendLine("    {");
            source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(system);");
            source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(actor);");
            source.AppendLine($"        return system.Spawn<{messageTypeName}>(actor, options);");
            source.AppendLine("    }");
            source.AppendLine();

            source.AppendLine($"    public static global::ULinkActor.ActorRef<{messageTypeName}> {methodName}(");
            source.AppendLine("        this global::ULinkActor.ActorSystem system,");
            source.AppendLine("        string name,");
            source.AppendLine($"        {actorTypeName} actor,");
            source.AppendLine("        global::ULinkActor.ActorSpawnOptions? options = null)");
            source.AppendLine("    {");
            source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(system);");
            source.AppendLine("        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(name);");
            source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(actor);");
            source.AppendLine($"        return system.Spawn<{messageTypeName}>(name, actor, options);");
            source.AppendLine("    }");
            source.AppendLine();
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static string SanitizeIdentifier(string value)
    {
        StringBuilder builder = new(value.Length);

        foreach (char ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return builder.Length == 0 ? "Actor" : builder.ToString();
    }
}
